### ISSUE TITLE
Necessity of Manual gcloud auth Injection in Direct Mode

### ISSUE THREAD

**Issue by hinewin** [pfnet-research/gcp-workload-identity-federation-webhook#44]
I've observed that the command `gcloud auth login --cred-file=$(CLOUDSDK_CONFIG)/federation.json` is used in the initialization container for the `gcloud` injection mode. However, it seems that the pod running in `direct` injection mode also requires both the installation of gcloud and the execution of  `gcloud auth login --cred-file=$(CLOUDSDK_CONFIG)/federation.json` within the container to function correctly. I couldn't seem to find these requirements documented anywhere and I'm seeking to confirm if they are indeed necessary for operating in `direct` mode.

**Comment by ordovicia** [comment]
In `direct` injection mode, `GOOGLE_APPLICATION_CREDENTIALS` environment variable is set, so you can run your application that uses the client library.
Please see also: https://cloud.google.com/docs/authentication/application-default-credentials

On the other hand, `CLOUDSDK_CONFIG` environment variable is not set (old README stated it is set, fixed by #43).
`gcloud` command will not work out of the box in `direct` mode.
I think we need to use non-direct mode to use `gcloud` command.

**Comment by superbrothers** [comment]
Fixed in #152.

`direct` mode now also injects `CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE` and a writable `gcloud-config` directory, so the `gcloud` CLI works out of the box in `direct` mode too. This will be included in the next release.
